import static org.kohsuke.args4j.ExampleMode.ALL;
import org.kohsuke.args4j.Argument;
import org.kohsuke.args4j.CmdLineException;
import org.kohsuke.args4j.CmdLineParser;
import org.kohsuke.args4j.Option;
import org.lightgrok.Indexer;
import org.lightgrok.PathProvider;
import org.lightgrok.Searcher;

import java.util.ArrayList;
import java.util.List;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class LightGrok {
    @Option(name="-root")
    String root = null;

    @Option(name="-search")
    String search = null;

    // receives other command line parameters than options
    @Argument
    private List<String> arguments = new ArrayList<String>();


    public String getUsage() {
        return "Usage: \n" +
            "  lightgrok -root directory    --> index directory with lightgrok \n" +
            "  lightgrok -root directory -search key    --> search directory's index with key \n";
    }


    public void doMain(String[] args) {
        CmdLineParser parser = new CmdLineParser(this);
        
        parser.setUsageWidth(80);

        try {
            parser.parseArgument(args);
        } catch (CmdLineException e) {
            System.err.println(e.getMessage());
            System.err.println("java LightGrok [options...] arguments...");
            parser.printUsage(System.err);
            System.err.println();
            return;
        }

        if (root != null && search == null) {
            System.out.println("root is: " + root);
            Indexer.createIndexerWithRoot(root).doIndex();
            return;
        }
        if (root != null && search != null) {
            System.out.println("search is: " + search);
            try {
                Searcher.createSearcherWithRoot(root).doSearch(search);
            } catch (Exception e) {
                e.printStackTrace();
            }
            return;
        }
        System.out.println( new LightGrok().getUsage());
    }

    public static void main(String[] args) {
        new LightGrok().doMain(args);
    }
}
